plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.16-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

tasks.register('republishLocal') {
    group = 'publishing'
    def repo = System.getProperty('maven.repo.local') ?: "${System.getProperty('user.home')}/.m2/repository"
    def target = file("${repo}/${project.group.toString().replace('.', '/')}")
    dependsOn allprojects.collect { it.tasks.matching { t -> t.name == 'build' } }
    doFirst { delete target }
    finalizedBy allprojects.collect { it.tasks.matching { t -> t.name == 'publishToMavenLocal' } }
}