org.gradle.jvmargs=-Xmx15G
org.gradle.daemon=false

minecraft_version=1.20.2
enabled_platforms=fabric,forge

archives_base_name=dimdoors
mod_version=5.4.1
maven_group=org.dimdev

architectury_version=9.1.12

fabric_loader_version=0.16.8
fabric_api_version=0.91.6+1.20.2

forge_version=1.20.2-48.1.0

parchment=2023.12.10

cardinal_components=5.3.0

iris=455508
iris_version=4861700

worldedit_CF=225608
worldedit_CF_version=4807512

wthitVersion=9.10.3

rei_version=13.1.773

cloth_config=12.0.137