org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

archives_base_name=dimdoors
mod_version=6.1.1
maven_group=org.dimdev

architectury_version=13.0.8

fabric_loader_version=0.16.14
fabric_api_version=0.116.6+1.21.1

neoforge_version=21.1.169

parchment=2024.11.17

iris=455508
iris_version=6213635

worldedit_CF=225608
worldedit_CF_version=5830452

wthitVersion=12.5.3

recipe_viewer=jei
rei=16.0.799
jei=19.21.0.247

cloth_config=15.0.140