org.gradle.jvmargs=-Xmx15G
org.gradle.daemon=false

minecraft_version=1.20.4
enabled_platforms=fabric,neoforge

archives_base_name=dimdoors
mod_version=5.4.1
maven_group=org.dimdev

architectury_version=11.1.17

fabric_loader_version=0.16.8
fabric_api_version=0.97.2+1.20.4

neoforge_version=20.4.237

parchment=2024.04.14

cardinal_components=5.4.0

iris=455508
iris_version=5485655

worldedit_CF=225608
worldedit_CF_version=5168651

wthitVersion=10.9.4

rei_version=14.1.786

cloth_config=14.0.125