package org.dimdev.dimdoors.item.door

import com.mojang.blaze3d.vertex.PoseStack
import com.mojang.math.Axis
import net.minecraft.core.Registry
import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.network.chat.Component
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.InteractionResult
import net.minecraft.world.item.*
import net.minecraft.world.item.context.BlockPlaceContext
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.DoorBlock
import net.minecraft.world.level.block.TrapDoorBlock
import org.apache.commons.lang3.tuple.ImmutableTriple
import org.apache.commons.lang3.tuple.Triple
import org.dimdev.dimcore.api.client.ToolTipHelper
import org.dimdev.dimcore.api.util.function.TriFunction
import org.dimdev.dimdoors.DimensionalDoors
import org.dimdev.dimdoors.DimensionalDoors.Companion.config
import org.dimdev.dimdoors.block.door.DimensionalDoorBlock
import org.dimdev.dimdoors.block.door.DimensionalTrapDoorBlock
import org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity
import org.dimdev.dimdoors.item.ItemExtensions
import org.dimdev.dimdoors.item.door.data.RiftDataList
import org.dimdev.dimdoors.rift.targets.EscapeTarget
import java.util.*
import java.util.function.Consumer
import java.util.function.Function

object DimensionalDoorItemRegistrar {
    private val blocksAlreadyNotifiedAbout: MutableMap<Block?, Block?> = HashMap<Block?, Block?>()
    private val toBeMapped: MutableMap<Block?, Triple<ResourceLocation?, Item?, Function<Block?, BlockItem?>?>> =
        HashMap<Block?, Triple<ResourceLocation?, Item?, Function<Block?, BlockItem?>?>>()
    private val mappedDoorItems: MutableMap<ResourceLocation?, ResourceLocation?> =
        HashMap<ResourceLocation?, ResourceLocation?>()
    val autogeneratedItems = mutableListOf<Item>()

    private val placementFunctions: MutableMap<Item?, Function<BlockPlaceContext?, InteractionResult?>?> =
        HashMap<Item?, Function<BlockPlaceContext?, InteractionResult?>?>()

    fun isRegistered(item: Item?): Boolean {
        return placementFunctions.containsKey(item)
    }

    fun place(item: Item?, context: BlockPlaceContext?): InteractionResult? {
        return placementFunctions.get(item)!!.apply(context)
    }

    fun handleEntry(identifier: ResourceLocation, original: Item?) {
        if (config.doorsConfig.isAllowed(identifier)) {
            if (original is DoubleHighBlockItem) {
                val block = original.getBlock()
                handleEntry(
                    identifier,
                    original,
                    block,
                    TriFunction { block: Block?, settings: Item.Properties?, originalItem: Item? ->
                        AutoGenDimensionalDoorBlockItem(
                            block,
                            settings,
                            originalItem
                        )
                    })
            } else if (original is BlockItem) {
                val originalBlock = original.getBlock()
                if (originalBlock is DoorBlock) {
                    handleEntry(
                        identifier,
                        original,
                        originalBlock,
                        TriFunction { block: Block?, settings: Item.Properties?, originalItem: Item? ->
                            AutoGenDimensionalDoorBlockItem(
                                block,
                                settings,
                                originalItem
                            )
                        })
                } else {
                    handleEntry(
                        identifier,
                        original,
                        originalBlock,
                        TriFunction { block: Block?, settings: Item.Properties?, originalItem: Item? ->
                            AutoGenDimensionalDoorTrapDoorItem(
                                block,
                                settings,
                                originalItem
                            )
                        })
                }
            }
        }
    }

    private fun handleEntry(
        identifier: ResourceLocation,
        original: Item?,
        originalBlock: Block?,
        constructor: TriFunction<Block?, Item.Properties?, Item?, out BlockItem?>
    ) {
        if ((originalBlock !is DimensionalDoorBlock<*>) && (originalBlock !is DimensionalTrapDoorBlock<*>) && (originalBlock is DoorBlock || originalBlock is TrapDoorBlock)) {
            val settings = ItemExtensions.getSettings(original)

            val dimItemConstructor = Function { dimBlock: Block? -> constructor.apply(dimBlock, settings, original) }

            if (!blocksAlreadyNotifiedAbout.containsKey(originalBlock)) {
                toBeMapped.put(
                    originalBlock,
                    ImmutableTriple<ResourceLocation?, Item?, Function<Block?, BlockItem?>?>(
                        identifier,
                        original,
                        dimItemConstructor
                    )
                )
                return
            }

            register(identifier, original, blocksAlreadyNotifiedAbout.get(originalBlock), dimItemConstructor)
        }
    }

    fun notifyBlockMapped(original: Block?, dimBlock: Block?) {
        blocksAlreadyNotifiedAbout.put(original, dimBlock)
        if (!toBeMapped.containsKey(original)) {
            return
        }
        val triple: Triple<ResourceLocation?, Item?, Function<Block?, BlockItem?>?> = toBeMapped.get(original)!!
        toBeMapped.remove(original)
        register(triple.getLeft()!!, triple.getMiddle(), dimBlock, triple.getRight()!!)
    }

    private fun register(
        identifier: ResourceLocation,
        original: Item?,
        block: Block?,
        dimItem: Function<Block?, BlockItem?>
    ) {
        if (placementFunctions.containsKey(original)) {
            return
        }
        val gennedId = DimensionalDoors.id(PREFIX + identifier.getNamespace() + "_" + identifier.getPath())
        val item = Registry.register<Item?, BlockItem>(BuiltInRegistries.ITEM, gennedId, dimItem.apply(block))
        mappedDoorItems.put(gennedId, identifier)
        autogeneratedItems.add(item)
        placementFunctions.put(original, Function { context: BlockPlaceContext? -> item.place(context) })
    }

    val generatedItemMappings: MutableMap<ResourceLocation?, ResourceLocation?>
        get() = Collections.unmodifiableMap<ResourceLocation?, ResourceLocation?>(
            mappedDoorItems
        )

    private open class AutoGenDimensionalDoorBlockItem(
        block: Block?,
        settings: Properties?,
        private val originalItem: Item?
    ) : EntranceRiftBlockItem(block, settings, null), ChildItem {
        override fun setupRift(entranceRift: EntranceRiftBlockEntity<*>) {
            val access = entranceRift.getLevel()!!.registryAccess()

            DoorRiftDataLoader.getRiftData(access, originalItem).ifPresentOrElse(Consumer { data: RiftDataList? ->
                val riftData = data!!.getRiftData(entranceRift)
                entranceRift.setDestination(riftData.getDestination())
                riftData.getProperties().ifPresent(entranceRift::properties)
            }, Runnable { entranceRift.setDestination(org.dimdev.dimdoors.rift.targets.PublicPocketTarget()) })
        }

        override fun getOriginalItem(): Item? {
            return originalItem
        }

        override fun appendHoverText(
            itemStack: ItemStack,
            world: TooltipContext?,
            list: MutableList<Component?>,
            tooltipContext: TooltipFlag
        ) {
            ToolTipHelper.processTranslation(list, this.getDescriptionId() + ".info")
        }
    }

    private class AutoGenDimensionalDoorTrapDoorItem(block: Block?, settings: Properties?, originalItem: Item?) :
        AutoGenDimensionalDoorBlockItem(block, settings, originalItem) {
        override fun transformOverlay(matrices: PoseStack) {
            matrices.translate(0.0, 0.0, 0.5 - (1 / 16f))
            matrices.mulPose(Axis.XP.rotationDegrees(90f))
        }

        override fun setupRift(entranceRift: EntranceRiftBlockEntity<*>) {
            DoorRiftDataLoader.getRiftData(entranceRift.getLevel()!!.registryAccess(), getOriginalItem())
                .ifPresentOrElse(
                    Consumer { data: RiftDataList? ->
                        val riftData = data!!.getRiftData(entranceRift)
                        entranceRift.setDestination(riftData.getDestination())
                        riftData.getProperties().ifPresent(entranceRift::properties)
                    }, Runnable { entranceRift.setDestination(EscapeTarget(true)) })
        }
    }

    interface ChildItem {
        @JvmField
        val originalItem: Item?

        fun transformOverlay(matrices: PoseStack?) {
        }

        fun transformUnderlay(matrices: PoseStack?) {
        }
    }

    companion object {
        const val PREFIX: String = "item_ag_dim_"
    }
}
