package org.dimdev.dimdoors.item.door

import com.mojang.blaze3d.vertex.PoseStack
import com.mojang.math.Axis
import net.minecraft.core.Registry
import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.network.chat.Component
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.InteractionResult
import net.minecraft.world.item.*
import net.minecraft.world.item.context.BlockPlaceContext
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.DoorBlock
import net.minecraft.world.level.block.TrapDoorBlock
import org.apache.commons.lang3.tuple.ImmutableTriple
import org.apache.commons.lang3.tuple.Triple
import org.dimdev.dimcore.api.client.ToolTipHelper
import org.dimdev.dimdoors.DimensionalDoors
import org.dimdev.dimdoors.DimensionalDoors.Companion.config
import org.dimdev.dimdoors.block.door.DimensionalDoorBlock
import org.dimdev.dimdoors.block.door.DimensionalTrapDoorBlock
import org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity
import org.dimdev.dimdoors.item.ItemExtensions
import org.dimdev.dimdoors.item.door.data.RiftDataList
import org.dimdev.dimdoors.rift.targets.EscapeTarget
import org.dimdev.dimdoors.rift.targets.PublicPocketTarget
import java.util.function.Consumer

object DimensionalDoorItemRegistrar {
    private val blocksAlreadyNotifiedAbout = mutableMapOf<Block, Block>()
    private val toBeMapped = mutableMapOf<Block, Triple<ResourceLocation, Item, (Block) -> BlockItem>>()
    private val mappedDoorItems= mutableMapOf<ResourceLocation, ResourceLocation>()
    val autogeneratedItems = mutableListOf<Item>()
    private val placementFunctions = mutableMapOf<Item, (BlockPlaceContext) -> InteractionResult?>()

    fun isRegistered(item: Item?): Boolean {
        return placementFunctions.containsKey(item)
    }

    fun place(item: Item, context: BlockPlaceContext) = placementFunctions[item]?.invoke(context)

    fun handleEntry(identifier: ResourceLocation, original: Item) {
        if (config.doorsConfig.isAllowed(identifier)) {
            if (original is DoubleHighBlockItem) {
                val block = original.block
                handleEntry(
                    identifier,
                    original,
                    block,
                    ::AutoGenDimensionalDoorBlockItem
                )
            } else if (original is BlockItem) {
                val originalBlock = original.block
                if (originalBlock is DoorBlock) {
                    handleEntry(identifier, original, originalBlock, ::AutoGenDimensionalDoorBlockItem)
                } else {
                    handleEntry(identifier, original, originalBlock, ::AutoGenDimensionalDoorTrapDoorItem)
                }
            }
        }
    }

    private fun handleEntry(
        identifier: ResourceLocation,
        original: Item,
        originalBlock: Block,
        constructor: (Block, Item.Properties, Item) -> BlockItem
    ) {
        if ((originalBlock !is DimensionalDoorBlock<*>) && (originalBlock !is DimensionalTrapDoorBlock<*>) && (originalBlock is DoorBlock || originalBlock is TrapDoorBlock)) {
            val settings = ItemExtensions.getSettings(original)

            val dimItemConstructor = { dimBlock: Block -> constructor.invoke(dimBlock, settings, original) }

            if (!blocksAlreadyNotifiedAbout.containsKey(originalBlock)) {
                toBeMapped[originalBlock] = ImmutableTriple(identifier, original, dimItemConstructor)
                return
            }

            blocksAlreadyNotifiedAbout[originalBlock]?.let { register(identifier, original, it, dimItemConstructor) }
        }
    }

    fun notifyBlockMapped(original: Block, dimBlock: Block) {
        blocksAlreadyNotifiedAbout[original] = dimBlock

        val triple: Triple<ResourceLocation, Item, (Block) -> BlockItem> = toBeMapped[original] ?: return
        toBeMapped.remove(original)
        register(triple.getLeft(), triple.getMiddle(), dimBlock, triple.getRight())
    }

    private fun register(
        identifier: ResourceLocation,
        original: Item,
        block: Block,
        dimItem: (Block) -> BlockItem
    ) {
        if (placementFunctions.containsKey(original)) {
            return
        }
        val gennedId = DimensionalDoors.id("$PREFIX${identifier.namespace}_${identifier.path}")
        val item = Registry.register(BuiltInRegistries.ITEM, gennedId, dimItem.invoke(block))
        mappedDoorItems[gennedId] = identifier
        autogeneratedItems.add(item)
        placementFunctions[original] = item::place
    }

    val generatedItemMappings: Map<ResourceLocation, ResourceLocation> get() = mappedDoorItems

    private open class AutoGenDimensionalDoorBlockItem(block: Block, settings: Properties, override val originalItem: Item) : EntranceRiftBlockItem(block, settings), ChildItem {

        override fun setupRift(entranceRift: EntranceRiftBlockEntity<*>) {
            val access = entranceRift.getLevel()!!.registryAccess()

            DoorRiftDataLoader.getRiftData(access, originalItem).ifPresentOrElse(Consumer { data: RiftDataList? ->
                val riftData = data!!.getRiftData(entranceRift)
                entranceRift.setDestination(riftData.copyDestination())
                riftData.properties?.let { entranceRift.properties = it }
            }) { entranceRift.setDestination(PublicPocketTarget) }
        }

        override fun appendHoverText(
            itemStack: ItemStack,
            world: TooltipContext,
            list: MutableList<Component>,
            tooltipContext: TooltipFlag
        ) {
            ToolTipHelper.processTranslation(list, "${this.descriptionId}.info")
        }
    }

    private class AutoGenDimensionalDoorTrapDoorItem(block: Block, settings: Properties, originalItem: Item) :
        AutoGenDimensionalDoorBlockItem(block, settings, originalItem) {


        override fun transformOverlay(matrices: PoseStack) {
            matrices.translate(0.0, 0.0, 0.5 - (1 / 16f))
            matrices.mulPose(Axis.XP.rotationDegrees(90f))
        }

        override fun setupRift(entranceRift: EntranceRiftBlockEntity<*>) {
            DoorRiftDataLoader.getRiftData(entranceRift.getLevel()!!.registryAccess(), originalItem)
                .ifPresentOrElse(
                    Consumer { data: RiftDataList? ->
                        val riftData = data!!.getRiftData(entranceRift)
                        entranceRift.setDestination(riftData.copyDestination())
                        riftData.properties?.let { entranceRift.properties = it }
                    }) { entranceRift.setDestination(EscapeTarget(true)) }
        }
    }

    interface ChildItem {
        val originalItem: Item

        fun transformOverlay(matrices: PoseStack) {
        }

        fun transformUnderlay(matrices: PoseStack) {
        }
    }

    const val PREFIX: String = "item_ag_dim_"
}
