package org.dimdev.dimdoors.rift.targets

import com.google.common.collect.Sets
import com.mojang.datafixers.Products.P8
import com.mojang.serialization.Codec
import com.mojang.serialization.codecs.RecordCodecBuilder
import net.minecraft.core.BlockPos
import net.minecraft.server.level.ServerLevel
import net.minecraft.world.level.levelgen.Heightmap
import org.apache.logging.log4j.LogManager
import org.apache.logging.log4j.Logger
import org.dimdev.dimcore.api.ext.cast
import org.dimdev.dimcore.api.ext.castOrNull
import org.dimdev.dimdoors.DimensionalDoors
import org.dimdev.dimdoors.api.rift.target.Target
import org.dimdev.dimdoors.api.util.Location
import org.dimdev.dimdoors.api.util.Location.Companion.ofWorld
import org.dimdev.dimdoors.api.util.math.MathUtil
import org.dimdev.dimdoors.block.ModBlocks
import org.dimdev.dimdoors.block.entity.DetachedRiftBlockEntity
import org.dimdev.dimdoors.block.entity.Rift
import org.dimdev.dimdoors.pockets.PocketGenerator
import org.dimdev.dimdoors.pockets.TemplateUtils
import org.dimdev.dimdoors.rift.registry.LinkProperties
import org.dimdev.dimdoors.rift.registry.PocketRegistry
import org.dimdev.dimdoors.rift.registry.RiftRegistry
import org.dimdev.dimdoors.world.pocket.VirtualLocation
import org.dimdev.dimdoors.world.pocket.type.Pocket
import java.util.stream.Collectors
import kotlin.math.*

abstract class RandomTarget<T : RandomTarget<T>>(
    val newRiftWeight: Float,
    val weightMaximum: Double,
    val coordFactor: Double,
    val positiveDepthFactor: Double,
    val negativeDepthFactor: Double,
    val acceptedGroups: MutableSet<Int>,
    val isNoLink: Boolean,
    val isNoLinkBack: Boolean
) : VirtualTarget<T>() {
    override fun receiveOther(): Target? { // TODO: Wrap rather than replace
        val virtualLocationHere = VirtualLocation.fromLocation(this.location)

        val riftWeights = calculateRiftWeights(virtualLocationHere)
        val selectedLink = if (riftWeights.isEmpty())
            if (this.newRiftWeight == -1f) null else return null
        else MathUtil.weightedRandom(riftWeights)


        // Check if we have to generate a new rift
        if (selectedLink == null) {
//             Randomly select a distance from the distribution f(x) = 1/(m^2/x + x)^2. We use the same distribution as the
//             weighting function. The idea is that there is some kind of "field" formed by the rift, with the field's
//             intensity decreasing proportionally to the area of the sphere. The product of the area of the sphere and
//             the intesity of the field at that radius is therefore constant, so the infinitsimal weight of any layer
//             will be constant and its weight will therefore simply be the original weight function at that value.
//
//             The inverse of the normalized distribution function can be generated by this Mathematica code:
//             distribution = 1/(m^2/x + x)^2
//             totalDistributionIntegral = Integrate[distribution, {x, 0, Infinity}, Assumptions -> m > 0];
//             normalizedDistribution = Simplify[distribution/totalDistributionIntegral]
//             cummulativeNormalizedDistribution = Simplify[Integrate[normalizedDistribution, x] - (Integrate[normalizedDistribution, x] /. x -> 0)]
//
//             m = 1; (*Doesn't matter which m you use, it's proportional*)
//             table = Table[{r, x /. FindRoot[cummulativeNormalizedDistribution - r, {x, m}]}, {r, 0.01, 0.99, 0.01}];
//             fit = NonlinearModelFit[table, m (2 Tan[Pi/2 x] + a Log[x] Sqrt[x]), {a}, x]
//             Show[ListPlot[table], Plot[fit[x], {x, 0, 1}]]
//             Clear[m];
//             inverseCummulativeNormalizedDistribution = Normal[fit]
            val r = Math.random()
            val distance = this.weightMaximum * (2 * tan(Math.PI / 2 * r) - 0.5578284481138029 * sqrt(r) * ln(r))

            // Randomly split the vector into depth, x, and z components
            // TODO: Two random angles isn't a uniformly random direction! Use random vector, normalize, add depth offset, scale xz, scale depth.
            val theta = Math.random() * Math.PI // Angle between vector and xz plane
            val phi = Math.random() * Math.PI // Angle of the vector on the xz plane relative to the x axis
            var depth = distance * sin(theta)
            depth /= if (depth > 0) this.positiveDepthFactor else this.negativeDepthFactor
            val x = cos(theta) * cos(phi) * distance / this.coordFactor
            val z = cos(theta) * sin(phi) * distance / this.coordFactor
            val virtualLocation = VirtualLocation(
                virtualLocationHere.world,
                virtualLocationHere.x + x.roundToInt(),
                virtualLocationHere.z + z.roundToInt(),
                virtualLocationHere.depth + depth.roundToInt()
            )

            if (virtualLocation.depth <= 0) {
                // This will lead to the overworld
                val world: ServerLevel = DimensionalDoors.getWorld(virtualLocation.world)!!
                var pos = world.getHeightmapPos(
                    Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
                    BlockPos(virtualLocation.x, 0, virtualLocation.z)
                )
                if (pos.y == -1) {
                    // No blocks at that XZ (hole in bedrock)
                    pos = BlockPos(virtualLocation.x, 0, virtualLocation.z)
                }

                world.setBlockAndUpdate(pos, ModBlocks.DETACHED_RIFT.defaultBlockState())

                val thisRift = this.location.blockEntity!!.cast<Rift>()
                val riftEntity = world.getBlockEntity(pos)!!.cast<DetachedRiftBlockEntity>()
                // TODO: Should the rift not be configured like the other link
                riftEntity.properties = thisRift.properties!!.toBuilder().linksRemaining(1).build()

                if (!this.isNoLinkBack && !riftEntity.properties!!.isOneWay) TemplateUtils.linkRifts(
                    ofWorld(
                        world,
                        pos
                    ), this.location
                )
                if (!this.isNoLink) TemplateUtils.linkRifts(this.location, ofWorld(world, pos))
                return riftEntity.`as`(Targets.ENTITY)
            } else {
                // Make a new dungeon pocket
                val thisRift = this.location.blockEntity as Rift?
                val newLink = if (thisRift!!.properties != null) thisRift.properties!!.toBuilder().linksRemaining(0)
                    .build() else null
                val linkBack = if (this.isNoLinkBack) NoneTarget else RiftReference(this.location)
                val pocket = generatePocket(
                    virtualLocation,
                    linkBack,
                    newLink
                ) // TODO make the generated dungeon of the same type, but in the overworld

                if (pocket == null) {
                    LOGGER.error("Failed to generate dungeon pocket at {} from {}.", virtualLocation, this.location)
                    return null
                }

                val entrance = PocketRegistry.instance.getPocketEntrance(pocket)
                if (!this.isNoLink) TemplateUtils.linkRifts(this.location, entrance)
                return entrance?.blockEntity?.castOrNull<Target>()
            }
        } else {
            // An existing rift was selected
            val riftEntity = selectedLink.blockEntity as Rift?

            // Link the rifts if necessary and teleport the entity
            if (!this.isNoLink) TemplateUtils.linkRifts(this.location, selectedLink)
            if (!this.isNoLinkBack && !riftEntity!!.properties!!.isOneWay) TemplateUtils.linkRifts(
                selectedLink,
                this.location
            )
            return riftEntity
        }
    }

    private fun calculateRiftWeights(virtualLocation: VirtualLocation): MutableMap<Location?, Float> {
        val weights = mutableMapOf<Location?, Float>()
        if (this.newRiftWeight > 0) weights[null] = this.newRiftWeight

        for (otherRift in RiftRegistry.instance.rifts) {
            val otherVirtualLocation = VirtualLocation.fromLocation(otherRift.location)
            if (otherRift.properties == null) continue
            val otherWeight = (if (otherRift.isDetached) otherRift.properties!!.floatingWeight else otherRift.properties!!.entranceWeight).toDouble()
            if (otherWeight == 0.0 || Sets.intersection(this.acceptedGroups, otherRift.properties!!.groups).isEmpty()) continue

            // Calculate the distance as sqrt((coordFactor * coordDistance)^2 + (depthFactor * depthDifference)^2)
            if (otherRift.properties!!.linksRemaining == 0) continue
            val depthDifference = (otherVirtualLocation.depth - virtualLocation.depth).toDouble()
            val coordDistance = sqrt(this.sq((otherVirtualLocation.x - virtualLocation.x).toDouble()) + this.sq((otherVirtualLocation.z - virtualLocation.z).toDouble())
            )
            val depthFactor = if (depthDifference > 0) this.positiveDepthFactor else this.negativeDepthFactor
            val distance = sqrt(this.sq(this.coordFactor * coordDistance) + this.sq(depthFactor * depthDifference))

            // Calculate the weight as 4m/pi w/(m^2/d + d)^2. This is similar to how gravitational/electromagnetic attraction
            // works in physics (G m1 m2/d^2 and k_e m1 m2/d^2). Even though we add a depth dimension to the world, we keep
            // the weight inversly proportionally to the area of a sphere (the square of the distance) rather than a
            // hypersphere (the cube of the area) because the y coordinate does not matter for now. We use m^2/d + d
            // rather than d such that the probability near 0 tends to 0 rather than infinity. f(m^2/d) is a special case
            // of f((m^(a+1)/a)/d^a). m is the location of f's maximum. The constant 4m/pi makes it such that a newRiftWeight
            // of 1 is equivalent to having a total link weight of 1 distributed equally across all layers.
            // TODO: We might want an a larger than 1 to make the function closer to 1/d^2
            val weight =
                4 * this.weightMaximum / Math.PI * otherWeight / this.sq(this.sq(this.weightMaximum) / distance + distance)
            weights[otherRift.location] = weight.toFloat()
        }

        return weights
    }

    protected open fun generatePocket(
        location: VirtualLocation,
        linkTo: VirtualTarget<*>,
        props: LinkProperties?
    ): Pocket<*, *>? {
        return PocketGenerator.generateDungeonPocketV2(location, linkTo, props)
    }

    private fun sq(a: Double): Double {
        return a * a
    }

    abstract class RandomTargetBuilder<T : RandomTarget<T>, V : RandomTargetBuilder<T, V>> internal constructor() {
        protected var newRiftWeight: Float = 0f
        protected var weightMaximum: Double = 0.0
        protected var coordFactor: Double = 0.0
        protected var positiveDepthFactor: Double = 0.0
        protected var negativeDepthFactor: Double = 0.0
        protected var acceptedGroups = mutableSetOf<Int>()
        protected var noLink: Boolean = false
        protected var noLinkBack: Boolean = false

        fun newRiftWeight(newRiftWeight: Float): V {
            this.newRiftWeight = newRiftWeight
            return cast()
        }

        fun weightMaximum(weightMaximum: Double): V {
            this.weightMaximum = weightMaximum
            return cast()
        }

        fun coordFactor(coordFactor: Double): V {
            this.coordFactor = coordFactor
            return cast()
        }

        fun positiveDepthFactor(positiveDepthFactor: Double): V {
            this.positiveDepthFactor = positiveDepthFactor
            return cast()
        }

        fun negativeDepthFactor(negativeDepthFactor: Double): V {
            this.negativeDepthFactor = negativeDepthFactor
            return cast()
        }

        fun acceptedGroups(acceptedGroups: MutableSet<Int>): V {
            this.acceptedGroups = acceptedGroups
            return cast()
        }

        fun noLink(noLink: Boolean): V {
            this.noLink = noLink
            return cast()
        }

        fun noLinkBack(noLinkBack: Boolean): V {
            this.noLinkBack = noLinkBack
            return cast()
        }

        abstract fun build(): T
    }

    companion object {
        private val LOGGER: Logger = LogManager.getLogger()

        fun <T : RandomTarget<T>> common(instance: RecordCodecBuilder.Instance<T>): P8<RecordCodecBuilder.Mu<T>, Float, Double, Double, Double, Double, MutableSet<Int>, Boolean, Boolean> = instance.group(
                Codec.FLOAT.fieldOf("newRiftWeight").forGetter{ obj -> obj.newRiftWeight },
                Codec.DOUBLE.fieldOf("weightMaximum").forGetter { obj -> obj.weightMaximum },
                Codec.DOUBLE.fieldOf("coordFactor").forGetter { obj -> obj.coordFactor },
                Codec.DOUBLE.fieldOf("positiveDepthFactor").forGetter { obj -> obj.positiveDepthFactor },
                Codec.DOUBLE.fieldOf("negativeDepthFactor").forGetter { obj -> obj.negativeDepthFactor },
                Codec.INT_STREAM.xmap(
                    { intStream -> intStream.boxed().collect(Collectors.toSet()) },
                    { integers -> integers.stream().mapToInt { obj -> obj } })
                    .fieldOf("acceptedGroups").forGetter { obj -> obj.acceptedGroups },
                Codec.BOOL.fieldOf("noLink").forGetter { obj -> obj.isNoLink },
                Codec.BOOL.fieldOf("noLinkBack").forGetter { obj -> obj.isNoLinkBack }
            )
    }
}
