version=6.3.0
mod_name=DimensionalDoors
mod_authors=StevenRS11, SenseiKiwi, Zixiken, Waterpicker, Robijnvogel, ZombieHDGaming, Runemoro
mod_id=dimdoors
license=MIT
credits=
description=Bend and twist reality, creating rifts, pocket dimensions, and much more.
