package org.dimdev.dimdoors.block.door;

import com.google.common.collect.BiMap;
import com.google.common.collect.HashBiMap;
import net.minecraft.client.resources.language.I18n;
import net.minecraft.core.Holder;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.Property;
import org.dimdev.dimdoors.DimensionalDoors;
import org.dimdev.limlib.api.ISided;
import org.dimdev.dimdoors.api.event.RegisterDimensionalDoorProductionsCallback;
import org.dimdev.dimdoors.block.AutoGenTraversalRiftBlock;
import org.dimdev.dimdoors.block.DoorSoundProvider;
import org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity;
import org.dimdev.dimdoors.block.entity.ModBlockEntityTypes;
import org.dimdev.dimdoors.item.door.DimensionalDoorItemRegistrar;
import org.dimdev.dimdoors.tag.ModBlockTags;
import org.dimdev.dimdoors.tag.ModItemTags;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.*;
import java.util.function.BiPredicate;

public class DimensionalDoorBlockRegistrar {
    public static final String PREFIX = "block_ag_dim_";

    private final ISided sided;
    private final DimensionalDoorItemRegistrar itemRegistrar;

    //The key is the id of the generated dimensional door and value is the key of the original block.
    private final BiMap<ResourceLocation, ResourceLocation> mappedDoorBlocks = HashBiMap.create();

    private final Map<ResourceLocation, DoorProduction> customDoorProductions = new HashMap<>();
    private final List<DoorProductionRule> customDoorProductionRules = new ArrayList<>();
    private boolean initialized;

    public Map<TagKey<Block>, List<Holder<Block>>> populateBlockTags(Map<TagKey<Block>, List<Holder<Block>>> map) {
        var registry = BuiltInRegistries.BLOCK;

        Map<ResourceKey<Block>, Holder<Block>> autoGeneratedDoorHolders = new HashMap<>(mappedDoorBlocks.size());
        mappedDoorBlocks.forEach((dimdoor, base) ->
                registry.getHolder(dimdoor).ifPresent(holder ->
                        autoGeneratedDoorHolders.put(ResourceKey.create(Registries.BLOCK, base), holder)
                )
        );

        if (autoGeneratedDoorHolders.isEmpty()) {
            return map;
        }

        Map<TagKey<Block>, List<Holder<Block>>> result = new HashMap<>(map.size());
        map.forEach((tag, holders) -> result.put(tag, new ArrayList<>(holders)));

        map.forEach((tag, holders) -> {
            if (tag.equals(BlockTags.MOB_INTERACTABLE_DOORS)) {
                return;
            }

            List<Holder<Block>> tagList = result.get(tag);

            for (Holder<Block> holder : holders) {
                holder.unwrapKey().ifPresent(key -> {
                    Holder<Block> autoGenHolder = autoGeneratedDoorHolders.get(key);
                    if (autoGenHolder != null) {
                        tagList.add(autoGenHolder);
                    }
                });
            }
        });

        result.put(ModBlockTags.DIMENSIONAL_DOORS, autoGeneratedDoorHolders.values().stream().toList());
        return result;
    }

    public Map<TagKey<Item>, List<Holder<Item>>> populateItemTags(Map<TagKey<Item>, List<Holder<Item>>> map) {
        var registry = BuiltInRegistries.BLOCK;

        Map<ResourceKey<Item>, Holder<Item>> autoGeneratedDoorHolders = new HashMap<>(mappedDoorBlocks.size());
        mappedDoorBlocks.forEach((dimdoor, base) ->
                registry.getHolder(dimdoor).map(Holder.Reference::value).map(Block::asItem).map(Item::builtInRegistryHolder).ifPresent(holder ->
                        autoGeneratedDoorHolders.put(ResourceKey.create(Registries.ITEM, base), holder)
                )
        );

        if (autoGeneratedDoorHolders.isEmpty()) {
            return map;
        }

        Map<TagKey<Item>, List<Holder<Item>>> result = new HashMap<>(map.size());
        map.forEach((tag, holders) -> result.put(tag, new ArrayList<>(holders)));

        map.forEach((tag, holders) -> {
            List<Holder<Item>> tagList = result.get(tag);

            for (var holder : holders) {
                holder.unwrapKey().ifPresent(key -> {
                    Holder<Item> autoGenHolder = autoGeneratedDoorHolders.get(key);
                    if (autoGenHolder != null) {
                        tagList.add(autoGenHolder);
                    }
                });
            }
        });

        result.put(ModItemTags.DIMENSIONAL_DOORS, autoGeneratedDoorHolders.values().stream().toList());
        return result;
    }

    public @Nullable Block getDimensionalVariant(Block block) {
        var id = block.builtInRegistryHolder().key().location();

        id = mappedDoorBlocks.inverse().get(id);

        if (id == null) return null;

        return BuiltInRegistries.BLOCK.get(id);
    }

    public interface DoorProduction {
        Block createDoor(GeneratedDoorContext context, DoorBlock originalBlock);

        Block createTrapdoor(GeneratedDoorContext context, TrapDoorBlock originalBlock);

        default void onBlockRegistered(GeneratedDoorContext context, Block generatedBlock) {
        }
    }

    @FunctionalInterface
    public interface DoorProductionSelector extends BiPredicate<ResourceLocation, Block> {
        @Override
        boolean test(ResourceLocation id, Block block);
    }

    private record DoorProductionRule(DoorProductionSelector selector, DoorProduction production) {
    }

    public record GeneratedDoorContext(
            ResourceLocation originalId,
            ResourceLocation generatedId,
            BlockBehaviour.Properties properties
    ) {
    }

    private static final DoorProduction DEFAULT_PRODUCTION = new DoorProduction() {
        @Override
        public Block createDoor(GeneratedDoorContext context, DoorBlock originalBlock) {
            return new DefaultAutoGenDoorBlock(context.properties(), originalBlock);
        }

        @Override
        public Block createTrapdoor(GeneratedDoorContext context, TrapDoorBlock originalBlock) {
            return new DefaultAutoGenTrapDoorBlock(context.properties(), originalBlock);
        }

        @Override
        public void onBlockRegistered(GeneratedDoorContext context, Block generatedBlock) {
            ModBlockEntityTypes.ENTRANCE_RIFT.addBlock(generatedBlock);
        }
    };

    public DimensionalDoorBlockRegistrar(ISided sided, DimensionalDoorItemRegistrar itemRegistrar) {
        this.sided = sided;
        this.itemRegistrar = itemRegistrar;
    }

    public void init() {
        if (initialized) {
            return;
        }
        RegisterDimensionalDoorProductionsCallback.EVENT.invoker().register(this);
        initialized = true;
        Registry<Block> blockRegistry = BuiltInRegistries.BLOCK;
        blockRegistry.holders().forEach(reference -> handleEntry(reference.key().location(), reference.value()));
        sided.registerCallback(blockRegistry, (registry, id, obj) -> handleEntry(id, obj));
    }

    public void handleEntry(ResourceLocation location, Block original) {
        if (DimensionalDoors.getConfig().getDoorsConfig().isAllowed(location)) {
            DoorProduction production = getProduction(location, original);
            if (!(original instanceof DimensionalDoorBlock) && original instanceof DoorBlock doorBlock) {
                registerDoor(location, doorBlock, production);
            } else if (!(original instanceof DimensionalTrapDoorBlock) && original instanceof TrapDoorBlock trapdoorBlock) {
                registerTrapdoor(location, trapdoorBlock, production);
            }
        }
    }

    private DoorProduction getProduction(ResourceLocation location, Block original) {
        DoorProduction production = customDoorProductions.get(location);
        if (production != null) {
            return production;
        }

        for (DoorProductionRule rule : customDoorProductionRules) {
            if (rule.selector().test(location, original)) {
                return rule.production();
            }
        }

        return DEFAULT_PRODUCTION;
    }

    private void registerDoor(ResourceLocation location, DoorBlock original, DoorProduction production) {
        ResourceLocation gennedId = generatedId(location);
        GeneratedDoorContext context = new GeneratedDoorContext(location, gennedId, createProperties(original));

        var result = production.createDoor(context, original);

        if(result != null) register(context, original, result, production);
    }

    private void registerTrapdoor(ResourceLocation location, TrapDoorBlock original, DoorProduction production) {
        ResourceLocation gennedId = generatedId(location);
        GeneratedDoorContext context = new GeneratedDoorContext(location, gennedId, createProperties(original));

        var result = production.createTrapdoor(context, original);

        if(result != null) register(context, original, result, production);
    }

    private void register(GeneratedDoorContext context, Block original, Block dimBlock, DoorProduction production) {
        if (mappedDoorBlocks.containsKey(context.generatedId())) return;

        dimBlock = sided.register(Registries.BLOCK, context.generatedId(), dimBlock);
        mappedDoorBlocks.put(context.generatedId(), context.originalId());
        itemRegistrar.notifyBlockMapped(original, dimBlock);

        production.onBlockRegistered(context, dimBlock);
    }

    private static ResourceLocation generatedId(ResourceLocation location) {
        return DimensionalDoors.id(PREFIX + location.getNamespace() + "_" + location.getPath());
    }

    private static BlockBehaviour.Properties createProperties(Block original) {
        return BlockBehaviour.Properties.ofFullCopy( original)
                .mapColor(original.defaultMapColor())
                .lightLevel(state -> originalStateWithSharedProperties(original, state).getLightEmission())
                .isValidSpawn((state, level, pos, type) -> originalStateWithSharedProperties(original, state).isValidSpawn(level, pos, type))
                .isRedstoneConductor((state, level, pos) -> originalStateWithSharedProperties(original, state).isRedstoneConductor(level, pos))
                .isSuffocating((state, level, pos) -> originalStateWithSharedProperties(original, state).isSuffocating(level, pos))
                .isViewBlocking((state, level, pos) -> originalStateWithSharedProperties(original, state).isViewBlocking(level, pos))
                .hasPostProcess((state, level, pos) -> originalStateWithSharedProperties(original, state).hasPostProcess(level, pos))
                .emissiveRendering((state, level, pos) -> originalStateWithSharedProperties(original, state).emissiveRendering(level, pos))
                .requiresCorrectToolForDrops();
    }

    private static BlockState originalStateWithSharedProperties(Block original, BlockState state) {
        BlockState originalState = original.defaultBlockState();

        for (Property<?> property : state.getProperties()) {
            if (originalState.hasProperty(property)) {
                originalState = transferProperty(state, originalState, property);
            }
        }

        return originalState;
    }

    public ResourceLocation get(ResourceLocation ResourceLocation) {
        return mappedDoorBlocks.get(ResourceLocation);
    }

    public void registerCustomDoorProduction(ResourceLocation id, DoorProduction production) {
        checkMutable("Custom dimensional door production for " + id);
        DoorProduction previous = customDoorProductions.putIfAbsent(id, production);
        if (previous != null && previous != production) {
            throw new IllegalArgumentException("Custom dimensional door production is already registered for " + id + ".");
        }
    }

    public void registerCustomDoorProduction(Collection<ResourceLocation> ids, DoorProduction production) {
        for (ResourceLocation id : ids) {
            registerCustomDoorProduction(id, production);
        }
    }

    public void registerCustomDoorProduction(DoorProductionSelector selector, DoorProduction production) {
        checkMutable("Custom dimensional door production rule");
        customDoorProductionRules.add(new DoorProductionRule(selector, production));
    }

    /**
     * Tag selectors only match tags that are already bound during block registration.
     * Datapack-only tags load too late to decide which generated block class to register.
     */
    public void registerCustomDoorProduction(TagKey<Block> tag, DoorProduction production) {
        registerCustomDoorProduction((id, block) -> block.builtInRegistryHolder().is(tag), production);
    }

    private void checkMutable(String message) {
        if (initialized) {
            throw new IllegalStateException(message + " must be registered before dimensional door block registration is initialized.");
        }
    }

    public boolean isMapped(ResourceLocation ResourceLocation) {
        return mappedDoorBlocks.containsKey(ResourceLocation);
    }

    public static <T extends Comparable<T>> BlockState transferProperty(BlockState from, BlockState to, Property<T> property) {
        return to.setValue(property, from.getValue(property));
    }

    public Set<ResourceLocation> getGennedIds() {
        return mappedDoorBlocks.keySet();
    }

    public static abstract class AutoGenDimensionalDoorBlock<T extends EntranceRiftBlockEntity> extends DimensionalDoorBlock<T> {


        protected final Block originalBlock;

        public AutoGenDimensionalDoorBlock(Properties settings, DoorSoundProvider originalBlock) {
            super(settings, originalBlock.getSetType(), !((Block) originalBlock).defaultBlockState().hasProperty(WATERLOGGED));
            this.originalBlock = (Block) originalBlock;

            StateDefinition.Builder<Block, BlockState> builder = new StateDefinition.Builder<>(this);
            this.createBlockStateDefinition(builder);
            this.stateDefinition = builder.create(Block::defaultBlockState, BlockState::new);

            BlockState state = this.getStateDefinition().any();
            BlockState originalState = this.originalBlock.defaultBlockState();
            for (Property<?> property : this.originalBlock.defaultBlockState().getProperties()) {
                if (state.hasProperty(property)) {
                    state = transferProperty(originalState, state, property);
                }
            }

            registerDefaultState(state.setValue(WATERLOGGED, false));
        }

        public static final List<Property<?>> EXISTING_DOOR_PROPERTIES = List.of(WATERLOGGED, DoorBlock.HALF, DoorBlock.OPEN, DoorBlock.FACING, DoorBlock.HINGE, DoorBlock.POWERED);

        @Override
        protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
            super.createBlockStateDefinition(builder);

            if (originalBlock != null) {
                originalBlock.defaultBlockState().getProperties().stream().filter(property -> !EXISTING_DOOR_PROPERTIES.contains(property)).forEach(builder::add);
            }
        }

        @Override
        public @NotNull MutableComponent getName() {


            return Component.translatable("dimdoors.autogen_block_prefix").append(originalBlock.getName());
        }

        public Block getOriginalBlock() {
            return originalBlock;
        }

        @Override
        public BlockState getVisualBlockState(BlockState state) {
            return getOriginalBlock().defaultBlockState().setValue(FACING, state.getValue(FACING)).setValue(OPEN, state.getValue(OPEN)).setValue(HINGE, state.getValue(HINGE)).setValue(POWERED, state.getValue(POWERED)).setValue(HALF, state.getValue(HALF));
        }
    }

    public static class DefaultAutoGenDoorBlock extends AutoGenDimensionalDoorBlock<EntranceRiftBlockEntity> {

        public DefaultAutoGenDoorBlock(Properties settings, DoorSoundProvider originalBlock) {
            super(settings, originalBlock);
        }

        @Override
        public BlockEntityType<EntranceRiftBlockEntity> getRiftBlockEnityType() {
            return ModBlockEntityTypes.ENTRANCE_RIFT;
        }
    }

    public static abstract class  AutoGenDimensionalTrapdoorBlock<T extends EntranceRiftBlockEntity> extends DimensionalTrapDoorBlock<T> implements AutoGenTraversalRiftBlock<T> {
        private final Block originalBlock;

        public AutoGenDimensionalTrapdoorBlock(Properties settings, DoorSoundProvider originalBlock) {
            super(settings, originalBlock.getSetType());
            this.originalBlock = (Block) originalBlock;

            StateDefinition.Builder<Block, BlockState> builder = new StateDefinition.Builder<>(this);
            this.createBlockStateDefinition(builder);
            this.stateDefinition = builder.create(Block::defaultBlockState, BlockState::new);

            BlockState state = this.getStateDefinition().any();
            BlockState originalState = this.originalBlock.defaultBlockState();
            for (Property<?> property : this.originalBlock.defaultBlockState().getProperties()) {
                if (state.hasProperty(property)) {
                    state = transferProperty(originalState, state, property);
                }
            }

            registerDefaultState(state.setValue(WATERLOGGED, false));
        }

        public static final List<Property<?>> EXISTING_TRAPDOOR_PROPERTIES = List.of(WATERLOGGED, TrapDoorBlock.HALF, TrapDoorBlock.OPEN, TrapDoorBlock.FACING, TrapDoorBlock.POWERED);

        @Override
        protected void createBlockStateDefinition(StateDefinition.@NotNull Builder<Block, BlockState> builder) {
            super.createBlockStateDefinition(builder);

            if(originalBlock != null) {
                originalBlock.defaultBlockState().getProperties().stream().filter(property -> !EXISTING_TRAPDOOR_PROPERTIES.contains(property)).forEach(builder::add);
            }
        }

        public Block getOriginalBlock() {
            return originalBlock;
        }

        @Override
        public BlockState getVisualBlockState(BlockState state) {
            return getOriginalBlock().defaultBlockState().setValue(FACING, state.getValue(FACING)).setValue(OPEN, state.getValue(OPEN)).setValue(POWERED, state.getValue(POWERED)).setValue(TrapDoorBlock.HALF, state.getValue(TrapDoorBlock.HALF));
        }
    }

    public static class DefaultAutoGenTrapDoorBlock extends AutoGenDimensionalTrapdoorBlock<EntranceRiftBlockEntity> {

        public DefaultAutoGenTrapDoorBlock(Properties settings, DoorSoundProvider originalBlock) {
            super(settings, originalBlock);
        }

        @Override
        public BlockEntityType<EntranceRiftBlockEntity> getRiftBlockEnityType() {
            return ModBlockEntityTypes.ENTRANCE_RIFT;
        }
    }
}
