package org.dimdev.dimdoors.block.door;

import com.google.common.collect.BiMap;
import com.google.common.collect.HashBiMap;
import net.minecraft.core.Holder;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityTicker;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.Property;
import org.dimdev.dimdoors.DimensionalDoors;
import org.dimdev.dimdoors.ISided;
import org.dimdev.dimdoors.api.block.entity.MutableBlockEntityType;
import org.dimdev.dimdoors.block.DoorSoundProvider;
import org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity;
import org.dimdev.dimdoors.block.entity.ModBlockEntityTypes;
import org.dimdev.dimdoors.block.entity.RiftBlockEntity;
import org.dimdev.dimdoors.item.door.DimensionalDoorItemRegistrar;
import org.dimdev.dimdoors.tag.ModBlockTags;
import org.dimdev.dimdoors.tag.ModItemTags;
import org.jetbrains.annotations.Nullable;

import java.util.*;
import java.util.function.BiFunction;

import static org.dimdev.dimdoors.block.DimensionalPortalBlock.checkType;

public class DimensionalDoorBlockRegistrar {
    public static final String PREFIX = "block_ag_dim_";

    private final ISided sided;
    private final DimensionalDoorItemRegistrar itemRegistrar;

    //The key is the id of the generated dimensional door and value is the key of the original block.
    private final BiMap<ResourceLocation, ResourceLocation> mappedDoorBlocks = HashBiMap.create();

    private final Map<ResourceLocation, AutoGenLogic<? extends RiftBlockEntity>> customDoorFunction = new HashMap<>();

    public Map<TagKey<Block>, List<Holder<Block>>> populateBlockTags(Map<TagKey<Block>, List<Holder<Block>>> map) {
        var registry = BuiltInRegistries.BLOCK;

        Map<ResourceKey<Block>, Holder<Block>> autoGeneratedDoorHolders = new HashMap<>(mappedDoorBlocks.size());
        mappedDoorBlocks.forEach((dimdoor, base) ->
                registry.getHolder(dimdoor).ifPresent(holder ->
                        autoGeneratedDoorHolders.put(ResourceKey.create(Registries.BLOCK, base), holder)
                )
        );

        if (autoGeneratedDoorHolders.isEmpty()) {
            return map;
        }

        Map<TagKey<Block>, List<Holder<Block>>> result = new HashMap<>(map.size());
        map.forEach((tag, holders) -> {
            result.put(tag, new ArrayList<>(holders));
        });

        map.forEach((tag, holders) -> {
            if (tag.equals(BlockTags.MOB_INTERACTABLE_DOORS)) {
                return;
            }

            List<Holder<Block>> tagList = result.get(tag);

            for (Holder<Block> holder : holders) {
                holder.unwrapKey().ifPresent(key -> {
                    Holder<Block> autoGenHolder = autoGeneratedDoorHolders.get(key);
                    if (autoGenHolder != null) {
                        tagList.add(autoGenHolder);
                    }
                });
            }
        });

        result.put(ModBlockTags.DIMENSIONAL_DOORS, autoGeneratedDoorHolders.values().stream().toList());
        return result;
    }

    public Map<TagKey<Item>, List<Holder<Item>>> populateItemTags(Map<TagKey<Item>, List<Holder<Item>>> map) {
        var registry = BuiltInRegistries.BLOCK;

        Map<ResourceKey<Item>, Holder<Item>> autoGeneratedDoorHolders = new HashMap<>(mappedDoorBlocks.size());
        mappedDoorBlocks.forEach((dimdoor, base) ->
                registry.getHolder(dimdoor).map(Holder.Reference::value).map(Block::asItem).map(Item::builtInRegistryHolder).ifPresent(holder ->
                        autoGeneratedDoorHolders.put(ResourceKey.create(Registries.ITEM, base), holder)
                )
        );

        if (autoGeneratedDoorHolders.isEmpty()) {
            return map;
        }

        Map<TagKey<Item>, List<Holder<Item>>> result = new HashMap<>(map.size());
        map.forEach((tag, holders) -> {
            result.put(tag, new ArrayList<>(holders));
        });

        map.forEach((tag, holders) -> {
            if (tag.equals(BlockTags.MOB_INTERACTABLE_DOORS)) {
                return;
            }

            List<Holder<Item>> tagList = result.get(tag);

            for (var holder : holders) {
                holder.unwrapKey().map(autoGeneratedDoorHolders::get).flatMap(Holder::unwrapKey).ifPresent(key -> {
                    Holder<Item> autoGenHolder = autoGeneratedDoorHolders.get(key);
                    if (autoGenHolder != null) {
                        tagList.add(autoGenHolder);
                    }
                });
            }
        });

        result.put(ModItemTags.DIMENSIONAL_DOORS, autoGeneratedDoorHolders.values().stream().toList());
        return result;
    }

    public @Nullable Block getDimensionalVariant(Block block) {
        var id = block.builtInRegistryHolder().key().location();

        id = mappedDoorBlocks.inverse().get(id);

        if (id == null) return null;

        return BuiltInRegistries.BLOCK.get(id);
    }

    public record AutoGenLogic<T extends RiftBlockEntity>(
            MutableBlockEntityType<T> blockEntityType,
            BiFunction<BlockBehaviour.Properties, DoorSoundProvider, Block> doorFunction,
            BiFunction<BlockBehaviour.Properties, DoorSoundProvider, Block> trapdoorFunction
    ) {
        public void register(Block block) {
            blockEntityType.addBlock(block);
        }
    }

    private static final AutoGenLogic<EntranceRiftBlockEntity> defaultLogic = new AutoGenLogic<>(ModBlockEntityTypes.ENTRANCE_RIFT,
            DimensionalDoorBlockRegistrar::createAutoGenDimensionalDoorBlock,
            DimensionalDoorBlockRegistrar::createAutoGenDimensionalTrapdoorBlock
    );

    public DimensionalDoorBlockRegistrar(ISided sided, DimensionalDoorItemRegistrar itemRegistrar) {
        this.sided = sided;
        this.itemRegistrar = itemRegistrar;

        Registry<Block> blockRegistry = BuiltInRegistries.BLOCK;
        blockRegistry.holders().forEach(reference -> handleEntry(reference.key().location(), reference.value()));
        sided.registerCallback(blockRegistry, (registry, id, obj) -> handleEntry(id, obj));
    }

    //TODO Figure out support for custom modded blocks.
    public void handleEntry(ResourceLocation location, Block original) {
        if (DimensionalDoors.getConfig().getDoorsConfig().isAllowed(location)) {
            if (!(original instanceof DimensionalDoorBlock) && original instanceof DoorBlock doorBlock) {
                register(location, doorBlock, customDoorFunction.getOrDefault(location, defaultLogic).doorFunction());
            } else if (!(original instanceof DimensionalTrapDoorBlock) && original instanceof TrapDoorBlock trapdoorBlock) {
                register(location, trapdoorBlock, customDoorFunction.getOrDefault(location, defaultLogic).trapdoorFunction());
            }
        }
    }

    private void register(ResourceLocation location, DoorSoundProvider original, BiFunction<BlockBehaviour.Properties, DoorSoundProvider, Block> constructor) {
        ResourceLocation gennedId = DimensionalDoors.id(PREFIX + location.getNamespace() + "_" + location.getPath());

        if (mappedDoorBlocks.containsKey(gennedId)) return;

        Block dimBlock = sided.register(Registries.BLOCK, gennedId, constructor.apply(BlockBehaviour.Properties.ofFullCopy((BlockBehaviour) original).requiresCorrectToolForDrops(), original));
        mappedDoorBlocks.put(gennedId, location);
        itemRegistrar.notifyBlockMapped((Block) original, dimBlock);

        var logic = customDoorFunction.getOrDefault(gennedId, defaultLogic);
        logic.register(dimBlock);
    }

    public ResourceLocation get(ResourceLocation ResourceLocation) {
        return mappedDoorBlocks.get(ResourceLocation);
    }

    public <T extends DoorBlock, K extends RiftBlockEntity> void registerCustomDoorLogic(ResourceLocation id, AutoGenLogic<K> logic) {
        customDoorFunction.putIfAbsent(id, logic);
    }

    public boolean isMapped(ResourceLocation ResourceLocation) {
        return mappedDoorBlocks.containsKey(ResourceLocation);
    }

    public static <T extends Comparable<T>> BlockState transferProperty(BlockState from, BlockState to, Property<T> property) {
        return to.setValue(property, from.getValue(property));
    }

    private static AutoGenDimensionalDoorBlock createAutoGenDimensionalDoorBlock(BlockBehaviour.Properties settings, DoorSoundProvider originalBlock) {
        return new AutoGenDimensionalDoorBlock(settings, originalBlock) {
            @Override
            protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
                appendPropertiesOverride(builder, (Block) originalBlock, WATERLOGGED);
            }
        };
    }

    private static AutoGenDimensionalTrapdoorBlock createAutoGenDimensionalTrapdoorBlock(BlockBehaviour.Properties settings, DoorSoundProvider originalBlock) {
        return new AutoGenDimensionalTrapdoorBlock(settings, originalBlock) {
            @Override
            protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
                appendPropertiesOverride(builder, (Block) originalBlock, WATERLOGGED);
            }
        };
    }

    private static void appendPropertiesOverride(StateDefinition.Builder<Block, BlockState> builder, Block originalBlock, Property<?>... requiredProperties) {
        HashSet<Property<?>> properties = new HashSet<>(originalBlock.getStateDefinition().getProperties());
        properties.addAll(List.of(requiredProperties));
        builder.add(properties.toArray(new Property[0]));
    }


    public Set<ResourceLocation> getGennedIds() {
        return mappedDoorBlocks.keySet();
    }

    public static class AutoGenDimensionalDoorBlock extends DimensionalDoorBlock {
        private final Block originalBlock;

        public AutoGenDimensionalDoorBlock(Properties settings, DoorSoundProvider originalBlock) {
            super(settings, originalBlock.getSetType());
            this.originalBlock = (Block) originalBlock;

            BlockState state = this.getStateDefinition().any();
            BlockState originalState = this.originalBlock.defaultBlockState();
            for (Property<?> property : this.originalBlock.defaultBlockState().getProperties()) {
                state = transferProperty(originalState, state, property);
            }
            registerDefaultState(state.setValue(WATERLOGGED, false));
        }

        @Override
        protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
            // This method has to be defined in an anonymous inner class,
            //     since Block#appendProperties is run before originalBlock can be set.
            throw new RuntimeException("AutoGenDimensionalDoorBlock should be instantiated as anonymous inner class overriding appendProperties!");
        }

        @Override
        public BlockState getEffectiveBlockState(BlockState state) {
            var baseState = originalBlock.defaultBlockState();

            return state.getProperties().stream()
                    .filter(baseState::hasProperty)
                    .reduce(
                            baseState,
                            (newState, property) -> transferProperty(state, newState, property),
                            (a, b) -> b
                    );
        }

        @Override
        public MutableComponent getName() {
            return Component.translatable("dimdoors.autogen_block_prefix").append(originalBlock.getName());
        }

        public Block getOriginalBlock() {
            return originalBlock;
        }

        @Nullable
        @Override
        public <T extends BlockEntity> BlockEntityTicker<T> getTicker(Level world, BlockState state, BlockEntityType<T> type) {
            return checkType(type, ModBlockEntityTypes.ENTRANCE_RIFT, (level, blockPos, blockState, blockEntity) -> blockEntity.tick(world, blockPos, blockState));
        }
    }

    public static class AutoGenDimensionalTrapdoorBlock extends DimensionalTrapDoorBlock {
        private final Block originalBlock;

        public AutoGenDimensionalTrapdoorBlock(Properties settings, DoorSoundProvider originalBlock) {
            super(settings, originalBlock.getSetType());
            this.originalBlock = (Block) originalBlock;

            BlockState state = this.getStateDefinition().any();
            BlockState originalState = this.originalBlock.defaultBlockState();
            for (Property<?> property : this.originalBlock.defaultBlockState().getProperties()) {
                state = transferProperty(originalState, state, property);
            }
            registerDefaultState(state.setValue(WATERLOGGED, false));
        }

        @Override
        protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
            // This method has to be defined in an anonymous inner class,
            //     since Block#appendProperties is run before originalBlock can be set.
            throw new RuntimeException("AutoGenDimensionalTrapdoorBlock should be instantiated as anonymous inner class overriding appendProperties!");
        }

        @Override
        public BlockState getEffectiveBlockState(BlockState state) {
            var baseState = originalBlock.defaultBlockState();

            return state.getProperties().stream()
                    .filter(baseState::hasProperty)
                    .reduce(
                            baseState,
                            (newState, property) -> transferProperty(state, newState, property),
                            (a, b) -> b
                    );
        }

        @Override
        public MutableComponent getName() {
            return Component.translatable("dimdoors.autogen_block_prefix").append(originalBlock.getName());
        }

        public Block getOriginalBlock() {
            return originalBlock;
        }

        @Nullable
        @Override
        public <T extends BlockEntity> BlockEntityTicker<T> getTicker(Level world, BlockState state, BlockEntityType<T> type) {
            return checkType(type, ModBlockEntityTypes.ENTRANCE_RIFT, (level, blockPos, blockState, blockEntity) -> blockEntity.tick(world, blockPos, blockState));
        }
    }
}
