plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    def interfaces = file('src/main/resources/interfaces.json')
    if (interfaces.exists()) {
        interfaceInjectionData.from(interfaces.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnlyApi "org.jetbrains:annotations:24.1.0"
    compileOnlyApi "org.apache.commons:commons-lang3:3.14.0"

    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly 'org.ow2.asm:asm-tree:9.6'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'

    compileOnly "net.caffeinemc:sodium-neoforge-mod:${sodium_version}+mc${minecraft_version}"

    api "dev.ryanhcode.sable:sable-common-${project.minecraft_version}:${project.sable_version}"
    api("dev.simulated_team.simulated:simulated-common-${project.minecraft_version}:${project.simulated_version}") {
        exclude group: "dev.ryanhcode.sable"
    }
    api("dev.eriksonn.aeronautics:aeronautics-common-${project.minecraft_version}:${project.aeronautics_version}") {
        exclude group: "dev.ryanhcode.sable"
    }
    compileOnlyApi "curse.maven:create-328085:7963363"

    api("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config}")

    compileOnlyApi "mcp.mobius.waila:wthit-api:neo-${wthitVersion}"

    api "org.jgrapht:jgrapht-core:1.1.0"
    api "maven.modrinth:iris:${iris_version}"
    api "com.github.DimensionalDevelopment:poly2tri.java:0.1.1"
    compileOnly "org.dimdev:limlib-common-${minecraft_version}:${limlib_version}"

    compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin:${rei}"

    compileOnlyApi "mezz.jei:jei-${minecraft_version}-lib:${jei}"
    compileOnlyApi "mezz.jei:jei-${minecraft_version}-common-api:${jei}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-common:${jei}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
