plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'

//    modImplementation("curse.maven:cyanide-541676:4824162")
//    // Remove the next line if you don't want to depend on the API
    api("dev.architectury:architectury:${project.properties["architectury_version"]}")
    api("me.shedaniel.cloth:cloth-config:${rootProject.properties["cloth_config_version"]}")
    compileOnlyApi("mcp.mobius.waila:wthit-api:fabric-${project.properties["wthit_version"]}")

    api("org.jgrapht:jgrapht-core:1.1.0")
    api("curse.maven:iris-${project.properties["iris"]}:${project.properties["iris_version"]}")
    api("curse.maven:worldedit-${project.properties["worldedit"]}:${project.properties["worldedit_version"]}")
    api("com.github.DimensionalDevelopment:poly2tri.java:0.1.1")

//    api("com.sk89q.worldedit:worldedit-core:${project.properties["worldedit"]}")

    compileOnly("me.shedaniel:RoughlyEnoughItems-api:${project.properties["rei_version"]}")
    compileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin:${project.properties["rei_version"]}")

    compileOnlyApi("mezz.jei:jei-${project.properties["minecraft_version"]}-lib:${project.properties["jei_version"]}")
    compileOnlyApi("mezz.jei:jei-${project.properties["minecraft_version"]}-common-api:${project.properties["jei_version"]}")
    runtimeOnly("mezz.jei:jei-${project.properties["minecraft_version"]}-common:${project.properties["jei_version"]}")
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

//
//sourceSets.main {
//    java {
//        srcDir("src/main/schematics")
//        srcDir("src/main/config")
//    }
//    resources.srcDirs("common/src/main/resources")
//}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}