modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "${mod_issues}"
displayURL = "${mod_sources}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''${description}'''
logoFile="${mod_id}.png
credits="${credits}"

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[accessTransformers]]
file="dimdoors.cfg"

[[dependencies.dimdoors]]
modId = "neoforge"
type="required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimdoors]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimdoors]]
modId = "architectury"
type="required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dimdoors]]
modId = "cloth_config"
type="required"
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"