modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "dimdoors"
version = "${version}"
displayName = "DimensionalDoors"
authors = "StevenRS11, SenseiKiwi, Zixiken, Waterpicker, Robijnvogel, ZombieHDGaming, Runemoro"
description = '''
Bend and twist reality, creating rifts, pocket dimensions, and much more
'''
#logoFile = ""

[[mixins]]
config="dimdoors.mixins.json"

[[mixins]]
config="dimdoors-common.mixins.json"

[[accessTransformers]]
file="dimdoors.cfg"

[[dependencies.dimdoors]]
modId = "neoforge"
type="required"
versionRange = "[20.+,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimdoors]]
modId = "minecraft"
type="required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimdoors]]
modId = "architectury"
type="required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dimdoors]]
modId = "cloth_config"
type="required"
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"