modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
# issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
# updateJSONURL = "https://change.me.example.invalid/updates.json"
# displayURL = "https://change.me.to.your.mods.homepage.example.invalid/"
credits = "${credits}"
authors = "${neoforge_mod_authors}"
enumExtensions = "META-INF/${mod_id}.enumextensions.json"
description = '''${description}'''
logoFile = "${mod_id}.png"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[mixins]]
config = "${mod_id}.sable_compat.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# [features.${mod_id}]
# openGLVersion = "[3.2,)"
