plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

def includeCompile(entry) {
    project.dependencies {
        api(entry)
        jarJar(entry)
    }
    neoForge.runs.configureEach {
        project.dependencies.add(additionalRuntimeClasspathConfiguration.name, entry)
    }
}

repositories {
    flatDir {
        dirs "${rootProject.projectDir}/.libs"
    }
}

dependencies {

    runtimeOnly("dev.ryanhcode.sable:sable-neoforge-${project.minecraft_version}:${project.sable_version}")
    runtimeOnly("dev.simulated_team.simulated:simulated-neoforge-${project.minecraft_version}:${project.simulated_version}")
    runtimeOnly("dev.eriksonn.aeronautics:aeronautics-neoforge-${project.minecraft_version}:${project.aeronautics_version}")

    includeCompile "org.jgrapht:jgrapht-core:1.1.0"
    includeCompile "com.github.DimensionalDevelopment:poly2tri.java:0.1.1"

    compileOnly "mcp.mobius.waila:wthit-api:neo-${wthitVersion}"
    compileOnly "mcp.mobius.waila:wthit:neo-${wthitVersion}"
    // modApi "lol.bai:badpackets:forge-0.4.2"
    // modApi "com.sk89q.worldedit:worldedit-forge-mc${world_edit_minecraft_version}:${worldedit}"
    compileOnly "curse.maven:worldedit-${worldedit_CF}:${worldedit_CF_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei}"
    compileOnlyApi "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei}"

    api("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config}")

//    switch (recipe_viewer?.toString()) {
//        case 'rei':
//            compileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-neoforge:${rei}"
//            break
//        case 'jei':
            runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei}"
//            break
//    }


    implementation "curse.maven:create-328085:7963363"
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    def interfaces = project(':common').file('src/main/resources/interfaces.json')
    if (interfaces.exists()) {
        interfaceInjectionData.from(interfaces.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
            logLevel = org.slf4j.event.Level.INFO
        }
        client {
            client()
        }
        data {
            data()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    srcDir project(':common').file('src/main/generated')
}
