package org.dimdev.dimdoors.item.door;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.math.Axis;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import org.apache.commons.lang3.tuple.ImmutableTriple;
import org.apache.commons.lang3.tuple.Triple;
import org.dimdev.dimdoors.DimensionalDoors;
import org.dimdev.dimdoors.ISided;
import org.dimdev.dimdoors.api.util.function.TriFunction;
import org.dimdev.dimdoors.block.door.DimensionalDoorBlock;
import org.dimdev.dimdoors.block.door.DimensionalTrapDoorBlock;
import org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity;
import org.dimdev.dimdoors.item.ItemExtensions;
import org.dimdev.dimdoors.item.door.data.RiftDataList;
import org.dimdev.dimdoors.rift.targets.EscapeTarget;
import org.dimdev.dimdoors.rift.targets.PublicPocketTarget;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

public class DimensionalDoorItemRegistrar {
    public static final String PREFIX = "item_ag_dim_";

    private final ISided sided;

    private final Map<Block, Block> blocksAlreadyNotifiedAbout = new HashMap<>();
    private final Map<Block, Triple<ResourceLocation, Item, Function<Block, BlockItem>>> toBeMapped = new HashMap<>();
    private final List<Item> autogeneratedItems = new ArrayList<>();

    private final Map<Item, Function<BlockPlaceContext, InteractionResult>> placementFunctions = new HashMap<>();

    public DimensionalDoorItemRegistrar(ISided sided) {
        this.sided = sided;
        var itemRegistry = BuiltInRegistries.ITEM;
        itemRegistry.holders().forEach(reference -> handleEntry(reference.key().location(), reference.value()));
        sided.registerCallback(itemRegistry, (registry, id, obj) -> handleEntry(id, obj));
    }

    public boolean isRegistered(Item item) {
    return placementFunctions.containsKey(item);
    }

    public InteractionResult place(Item item, BlockPlaceContext context) {
        return placementFunctions.get(item).apply(context);
    }

    public void handleEntry(ResourceLocation identifier, Item original) {
        if (DimensionalDoors.getConfig().getDoorsConfig().isAllowed(identifier)) {
            if (original instanceof DoubleHighBlockItem doubleHighBlockItem) {
                Block block = doubleHighBlockItem.getBlock();
                handleEntry(identifier, original, block, AutoGenDimensionalDoorBlockItem::new);
            } else if (original instanceof BlockItem) {
                Block originalBlock = ((BlockItem) original).getBlock();
                if (originalBlock instanceof DoorBlock) {
                    handleEntry(identifier, original, originalBlock, AutoGenDimensionalDoorBlockItem::new);
                } else {
                    handleEntry(identifier, original, originalBlock, AutoGenDimensionalDoorTrapDoorItem::new);
                }
            }
        }
    }

    private void handleEntry(ResourceLocation identifier, Item original, Block originalBlock, TriFunction<Block, Item.Properties, Item, ? extends BlockItem> constructor) {

        if (!(originalBlock instanceof DimensionalDoorBlock)
                && !(originalBlock instanceof DimensionalTrapDoorBlock)
                && (originalBlock instanceof DoorBlock || originalBlock instanceof TrapDoorBlock)) {
            Item.Properties settings = ItemExtensions.getSettings(original);

            Function<Block, BlockItem> dimItemConstructor = (dimBlock) -> constructor.apply(dimBlock, settings, original);

            if (!blocksAlreadyNotifiedAbout.containsKey(originalBlock)) {
                toBeMapped.put(originalBlock, new ImmutableTriple<>(identifier, original, dimItemConstructor));
                return;
            }

            register(identifier, original, blocksAlreadyNotifiedAbout.get(originalBlock), dimItemConstructor);
        }
    }

    public void notifyBlockMapped(Block original, Block dimBlock) {
        if (!toBeMapped.containsKey(original)) {
            blocksAlreadyNotifiedAbout.put(original, dimBlock);
            return;
        }
        Triple<ResourceLocation, Item, Function<Block, BlockItem>> triple = toBeMapped.get(original);
        register(triple.getLeft(), triple.getMiddle(), dimBlock, triple.getRight());
    }

    private void register(ResourceLocation identifier, Item original, Block block, Function<Block, BlockItem> dimItem) {
        ResourceLocation gennedId = DimensionalDoors.id(PREFIX + identifier.getNamespace() + "_" + identifier.getPath());
        BlockItem item = sided.register(Registries.ITEM, gennedId, dimItem.apply(block));
        autogeneratedItems.add(item);
        placementFunctions.put(original, item::place);
        if (DimensionalDoors.getSided().isClient()) {
            registerItemRenderer(item);
        }
    }

    public List<Item> getAutogeneratedItems() {
        return autogeneratedItems;
    }

    @Environment(EnvType.CLIENT)
    private void registerItemRenderer(BlockItem dimItem) {
//    BuiltinItemRendererRegistry.INSTANCE.register(dimItem, Renderer.RENDERER); TODO: Enable
    }

    private static class AutoGenDimensionalDoorBlockItem extends DimensionalDoorBlockItem implements ChildItem {
    private final Item originalItem;

    public AutoGenDimensionalDoorBlockItem(Block block, Properties settings, Item originalItem) {
        super(block, settings, null);
        this.originalItem = originalItem;
    }

    @Override
    public void setupRift(EntranceRiftBlockEntity entranceRift) {
        RiftDataList data = DoorRiftDataLoader.getRiftData(originalItem);
        if (data != null) {
        RiftDataList.OptRiftData riftData = data.getRiftData(entranceRift);
        entranceRift.setDestination(riftData.getDestination());
        riftData.getProperties().ifPresent(entranceRift::setProperties);
        } else {
        entranceRift.setDestination(new PublicPocketTarget());
        }
    }

    @Override
    public MutableComponent getName(ItemStack stack) {
        return Component.translatable("dimdoors.autogen_item_prefix").append(originalItem.getDescription());
    }

    @Override
    public Item getOriginalItem() {
        return originalItem;
    }
    }

    private static class AutoGenDimensionalDoorTrapDoorItem extends AutoGenDimensionalDoorBlockItem {

        public AutoGenDimensionalDoorTrapDoorItem(Block block, Properties settings, Item originalItem) {
            super(block, settings, originalItem);
        }

        @Override
        public void transformOverlay(PoseStack matrices) {
            matrices.translate(0, 0, 0.5 - (1/16f));
            matrices.mulPose(Axis.XP.rotationDegrees(90));
        }

        @Override
        public void setupRift(EntranceRiftBlockEntity entranceRift) {
            RiftDataList data = DoorRiftDataLoader.getRiftData(getOriginalItem());
            if (data != null) {
                RiftDataList.OptRiftData riftData = data.getRiftData(entranceRift);
                entranceRift.setDestination(riftData.getDestination());
                riftData.getProperties().ifPresent(entranceRift::setProperties);
            } else {
                entranceRift.setDestination(new EscapeTarget(true));
            }
        }

    }

    public interface ChildItem {
    Item getOriginalItem();

    default void transformOverlay(PoseStack matrices) {
    }

        default void transformUnderlay(PoseStack matrices) {

        }
    }
}