package org.dimdev.dimdoors.item.door;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.math.Axis;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import org.apache.commons.lang3.tuple.ImmutableTriple;
import org.apache.commons.lang3.tuple.Triple;
import org.dimdev.dimdoors.DimensionalDoors;
import org.dimdev.limlib.api.ISided;
import org.dimdev.limlib.api.client.ToolTipHelper;
import org.dimdev.limlib.api.util.function.TriFunction;
import org.dimdev.dimdoors.block.door.DimensionalDoorBlock;
import org.dimdev.dimdoors.block.door.DimensionalTrapDoorBlock;
import org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity;
import org.dimdev.dimdoors.item.ItemExtensions;
import org.dimdev.dimdoors.item.door.data.RiftDataList;
import org.dimdev.dimdoors.rift.targets.EscapeTarget;
import org.dimdev.dimdoors.rift.targets.PublicPocketTarget;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

import static org.dimdev.dimdoors.item.door.DoorRiftDataLoader.getRiftData;

public class DimensionalDoorItemRegistrar {
    public static final String PREFIX = "item_ag_dim_";

    private final ISided<?> sided;

    private final Map<Block, Block> blocksAlreadyNotifiedAbout = new HashMap<>();
    private final Map<Block, Triple<ResourceLocation, Item, Function<Block, BlockItem>>> toBeMapped = new HashMap<>();
    private final Map<ResourceLocation, ResourceLocation> mappedDoorItems = new HashMap<>();
    private final List<Item> autogeneratedItems = new ArrayList<>();

    private final Map<Item, Function<BlockPlaceContext, InteractionResult>> placementFunctions = new HashMap<>();
    private boolean initialized;

    public DimensionalDoorItemRegistrar(ISided<?> sided) {
        this.sided = sided;
    }

    public void init() {
        if (initialized) {
            return;
        }
        initialized = true;
        var itemRegistry = BuiltInRegistries.ITEM;
        itemRegistry.holders().forEach(reference -> handleEntry(reference.key().location(), reference.value()));
        sided.registerCallback(itemRegistry, (registry, id, obj) -> handleEntry(id, obj));
    }

    public boolean isRegistered(Item item) {
    return placementFunctions.containsKey(item);
    }

    public InteractionResult place(Item item, BlockPlaceContext context) {
        return placementFunctions.get(item).apply(context);
    }

    public void handleEntry(ResourceLocation identifier, Item original) {
        if (DimensionalDoors.getConfig().getDoorsConfig().isAllowed(identifier)) {
            if (original instanceof DoubleHighBlockItem doubleHighBlockItem) {
                Block block = doubleHighBlockItem.getBlock();
                handleEntry(identifier, original, block, AutoGenDimensionalDoorBlockItem::new);
            } else if (original instanceof BlockItem) {
                Block originalBlock = ((BlockItem) original).getBlock();
                if (originalBlock instanceof DoorBlock) {
                    handleEntry(identifier, original, originalBlock, AutoGenDimensionalDoorBlockItem::new);
                } else {
                    handleEntry(identifier, original, originalBlock, AutoGenDimensionalDoorTrapDoorItem::new);
                }
            }
        }
    }

    private void handleEntry(ResourceLocation identifier, Item original, Block originalBlock, TriFunction<Block, Item.Properties, Item, ? extends BlockItem> constructor) {

        if (!(originalBlock instanceof DimensionalDoorBlock)
                && !(originalBlock instanceof DimensionalTrapDoorBlock)
                && (originalBlock instanceof DoorBlock || originalBlock instanceof TrapDoorBlock)) {
            Item.Properties settings = ItemExtensions.getSettings(original);

            Function<Block, BlockItem> dimItemConstructor = (dimBlock) -> constructor.apply(dimBlock, settings, original);

            if (!blocksAlreadyNotifiedAbout.containsKey(originalBlock)) {
                toBeMapped.put(originalBlock, new ImmutableTriple<>(identifier, original, dimItemConstructor));
                return;
            }

            register(identifier, original, blocksAlreadyNotifiedAbout.get(originalBlock), dimItemConstructor);
        }
    }

    public void notifyBlockMapped(Block original, Block dimBlock) {
        blocksAlreadyNotifiedAbout.put(original, dimBlock);
        if (!toBeMapped.containsKey(original)) {
            return;
        }
        Triple<ResourceLocation, Item, Function<Block, BlockItem>> triple = toBeMapped.get(original);
        toBeMapped.remove(original);
        register(triple.getLeft(), triple.getMiddle(), dimBlock, triple.getRight());
    }

    private void register(ResourceLocation identifier, Item original, Block block, Function<Block, BlockItem> dimItem) {
        if (placementFunctions.containsKey(original)) {
            return;
        }
        ResourceLocation gennedId = DimensionalDoors.id(PREFIX + identifier.getNamespace() + "_" + identifier.getPath());
        BlockItem item = sided.register(Registries.ITEM, gennedId, dimItem.apply(block));
        mappedDoorItems.put(gennedId, identifier);
        autogeneratedItems.add(item);
        placementFunctions.put(original, item::place);
    }

    public List<Item> getAutogeneratedItems() {
        return autogeneratedItems;
    }

    public Map<ResourceLocation, ResourceLocation> getGeneratedItemMappings() {
        return Collections.unmodifiableMap(mappedDoorItems);
    }

    private static class AutoGenDimensionalDoorBlockItem extends EntranceRiftBlockItem implements ChildItem {
        private final Item originalItem;

        public AutoGenDimensionalDoorBlockItem(Block block, Properties settings, Item originalItem) {
            super(block, settings, null);
            this.originalItem = originalItem;
        }

        @Override
        public void setupRift(EntranceRiftBlockEntity entranceRift) {
            var access = entranceRift.getLevel().registryAccess();

            getRiftData(access, originalItem).ifPresentOrElse(data -> {
                RiftDataList.OptRiftData riftData = data.getRiftData(entranceRift);
                entranceRift.setDestination(riftData.getDestination());
                riftData.getProperties().ifPresent(entranceRift::setProperties);
            }, () -> entranceRift.setDestination(new PublicPocketTarget()));
        }

        @Override
        public Item getOriginalItem() {
            return originalItem;
        }

        @Override
        public void appendHoverText(ItemStack itemStack, @Nullable TooltipContext world, List<Component> list, TooltipFlag tooltipContext) {
            ToolTipHelper.processTranslation(list, this.getDescriptionId() + ".info");
        }
    }

    private static class AutoGenDimensionalDoorTrapDoorItem extends AutoGenDimensionalDoorBlockItem {

        public AutoGenDimensionalDoorTrapDoorItem(Block block, Properties settings, Item originalItem) {
            super(block, settings, originalItem);
        }

        @Override
        public void transformOverlay(PoseStack matrices) {
            matrices.translate(0, 0, 0.5 - (1/16f));
            matrices.mulPose(Axis.XP.rotationDegrees(90));
        }

        @Override
        public void setupRift(EntranceRiftBlockEntity entranceRift) {
            getRiftData(entranceRift.getLevel().registryAccess(), getOriginalItem()).ifPresentOrElse(data -> {
                RiftDataList.OptRiftData riftData = data.getRiftData(entranceRift);
                entranceRift.setDestination(riftData.getDestination());
                riftData.getProperties().ifPresent(entranceRift::setProperties);
            }, () -> entranceRift.setDestination(new EscapeTarget(true)));
        }

    }

    public interface ChildItem {
    Item getOriginalItem();

    default void transformOverlay(PoseStack matrices) {
    }

        default void transformUnderlay(PoseStack matrices) {

        }
    }
}
