package org.dimdev.dimdoors.block.door

import com.google.common.collect.HashBiMap
import net.minecraft.core.BlockPos
import net.minecraft.core.Holder
import net.minecraft.core.Registry
import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.resources.ResourceKey
import net.minecraft.resources.ResourceLocation
import net.minecraft.tags.TagKey
import net.minecraft.world.entity.player.Player
import net.minecraft.world.item.Item
import net.minecraft.world.level.Level
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.DoorBlock
import net.minecraft.world.level.block.TrapDoorBlock
import net.minecraft.world.level.block.entity.BlockEntityType
import net.minecraft.world.level.block.state.BlockBehaviour
import net.minecraft.world.level.block.state.BlockState
import net.minecraft.world.level.block.state.StateDefinition
import net.minecraft.world.level.block.state.properties.Property
import net.minecraft.world.phys.BlockHitResult
import org.dimdev.dimcore.api.ext.cast
import org.dimdev.dimdoors.DimensionalDoors
import org.dimdev.dimdoors.DimensionalDoors.Companion.config
import org.dimdev.dimdoors.api.event.RegisterDimensionalDoorProductionsCallback
import org.dimdev.dimdoors.block.AutoGenTraversalRiftBlock
import org.dimdev.dimdoors.block.DoorSoundProvider
import org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity
import org.dimdev.dimdoors.block.entity.ModBlockEntityTypes
import org.dimdev.dimdoors.item.door.DimensionalDoorItemRegistrar
import org.dimdev.dimdoors.tag.ModBlockTags
import org.dimdev.dimdoors.tag.ModItemTags
import kotlin.jvm.optionals.getOrNull

typealias TagMap<T> = MutableMap<TagKey<T>, MutableList<Holder<T>>>

typealias BlockTagMap = TagMap<Block>
typealias ItemTagMap = TagMap<Item>

object DimensionalDoorBlockRegistrar {
    private val mappedDoorBlocks = HashBiMap.create<ResourceLocation, ResourceLocation>()

    private val customDoorProductions = mutableMapOf<ResourceLocation, DoorProduction>()
    private val customDoorProductionRules = mutableListOf<DoorProductionRule>()
    private var initialized = false

    fun <T> populateTags(
        registry: Registry<T>,
        map: TagMap<T>,
        doorTag: TagKey<T>,
        predicate: TagKey<T>.() -> Boolean
    ): TagMap<T> {
        val key = registry.key()

        val autoGenerated = mappedDoorBlocks
            .mapNotNull { (dimdoor, base) ->
                registry.getHolder(dimdoor)
                    .getOrNull()?.let { ResourceKey.create(key, base) to it }
            }.toMap()

        val result: TagMap<T> = map.mapValuesTo(mutableMapOf()) { (tag, holders) ->
            if (tag.let(predicate)) holders.toMutableList()
            else (holders + holders.mapNotNull { it.unwrapKey().getOrNull()?.let(autoGenerated::get) }).toMutableList()
        }
        result[doorTag] = autoGenerated.values.toMutableList<Holder<T>>()
        return result
    }

    fun populateBlockTags(map: BlockTagMap): BlockTagMap =
        populateTags(BuiltInRegistries.BLOCK, map, ModBlockTags.DIMENSIONAL_DOORS) { false }

    fun populateItemTags(map: ItemTagMap): ItemTagMap =
        populateTags(BuiltInRegistries.ITEM, map, ModItemTags.DIMENSIONAL_DOORS) { false }

    fun getDimensionalVariant(block: Block): Block? {
        var id = block.builtInRegistryHolder().key().location()
        id = mappedDoorBlocks.inverse()[id] ?: return null

        return BuiltInRegistries.BLOCK.get(id)
    }

    interface DoorProduction {
        fun createDoor(context: GeneratedDoorContext, originalBlock: DoorBlock): Block?

        fun createTrapdoor(context: GeneratedDoorContext, originalBlock: TrapDoorBlock): Block?

        fun onBlockRegistered(context: GeneratedDoorContext, generatedBlock: Block) {
        }
    }

    fun interface DoorProductionSelector {
        fun test(id: ResourceLocation?, block: Block?): Boolean
    }

    private data class DoorProductionRule(val selector: DoorProductionSelector, val production: DoorProduction)

    @JvmRecord
    data class GeneratedDoorContext(
        val originalId: ResourceLocation,
        val generatedId: ResourceLocation,
        val properties: BlockBehaviour.Properties
    )

    fun handleEntry(location: ResourceLocation, original: Block) {
        if (!initialized) {
            RegisterDimensionalDoorProductionsCallback.EVENT.invoker().register(this)
            initialized = true
        }

        if (config.doorsConfig.isAllowed(location)) {
            val production = getProduction(location, original)
            if (original !is DimensionalDoorBlock<*> && original is DoorBlock) {
                registerDoor(location, original, production)
            } else if (original !is DimensionalTrapDoorBlock<*> && original is TrapDoorBlock) {
                registerTrapdoor(location, original, production)
            }
        }
    }

    private fun getProduction(location: ResourceLocation, original: Block): DoorProduction {
        val production = customDoorProductions.get(location)
        if (production != null) {
            return production
        }

        for (rule in customDoorProductionRules) {
            if (rule.selector.test(location, original)) {
                return rule.production
            }
        }

        return DEFAULT_PRODUCTION
    }

    private fun registerDoor(location: ResourceLocation, original: DoorBlock, production: DoorProduction) {
        val gennedId: ResourceLocation = generatedId(location)
        val context = GeneratedDoorContext(location, gennedId, createProperties(original))

        val result = production.createDoor(context, original)

        if (result != null) register(context, original, result, production)
    }

    private fun registerTrapdoor(location: ResourceLocation, original: TrapDoorBlock, production: DoorProduction) {
        val gennedId: ResourceLocation = generatedId(location)
        val context = GeneratedDoorContext(location, gennedId, createProperties(original))

        val result = production.createTrapdoor(context, original)

        if (result != null) register(context, original, result, production)
    }

    private fun register(context: GeneratedDoorContext, original: Block, dimBlock: Block, production: DoorProduction) {
        var dimBlock = dimBlock
        if (mappedDoorBlocks.containsKey(context.generatedId)) return

        dimBlock = Registry.register(BuiltInRegistries.BLOCK, context.generatedId, dimBlock)
        mappedDoorBlocks[context.generatedId] = context.originalId
        DimensionalDoorItemRegistrar.notifyBlockMapped(original, dimBlock)

        production.onBlockRegistered(context, dimBlock)
    }

    operator fun get(location: ResourceLocation?): ResourceLocation? {
        return mappedDoorBlocks[location]
    }

    fun registerCustomDoorProduction(id: ResourceLocation, production: DoorProduction) {
        checkMutable("Custom dimensional door production for $id")
        val previous = customDoorProductions.putIfAbsent(id, production)
        require(!(previous != null && previous !== production)) { "Custom dimensional door production is already registered for $id." }
    }

    fun registerCustomDoorProduction(ids: MutableCollection<ResourceLocation>, production: DoorProduction) {
        for (id in ids) {
            registerCustomDoorProduction(id, production)
        }
    }

    fun registerCustomDoorProduction(selector: DoorProductionSelector, production: DoorProduction) {
        checkMutable("Custom dimensional door production rule")
        customDoorProductionRules.add(DoorProductionRule(selector, production))
    }

//    /**
//     * Tag selectors only match tags that are already bound during block registration.
//     * Datapack-only tags load too late to decide which generated block class to register.
//     */
//    fun registerCustomDoorProduction(tag: TagKey<Block>, production: DoorProduction) {
//        registerCustomDoorProduction({ id: ResourceLocation, block: Block -> block.builtInRegistryHolder().`is`(tag) }, production)
//    }

    private fun checkMutable(message: String) {
        check(!initialized) { "$message must be registered before dimensional door block registration is initialized." }
    }

    fun isMapped(location: ResourceLocation): Boolean = mappedDoorBlocks.containsKey(location)

    val gennedIds: MutableSet<ResourceLocation?>
        get() = mappedDoorBlocks.keys

    val generatedBlockMappings: MutableMap<ResourceLocation, ResourceLocation>
        get() = mappedDoorBlocks


    abstract class AutoGenDimensionalDoorBlock<T : EntranceRiftBlockEntity<*>>(
        settings: Properties,
        originalBlock: DoorSoundProvider
    ) : DimensionalDoorBlock<T>(
        settings, originalBlock.setType, !(originalBlock as Block).defaultBlockState().hasProperty(WATERLOGGED)
    ) {
        val originalBlock: Block = originalBlock as Block

        init {

            val builder = StateDefinition.Builder<Block, BlockState>(this)
            this.createBlockStateDefinition(builder)
            this.stateDefinition = builder.create(
                { obj: Block -> obj.defaultBlockState() },
                ::BlockState
            )

            registerDefaultState(stateDefinition.any())
            registerDefaultState(
                withPropertiesOf(this.originalBlock.defaultBlockState()).setValue(
                    TrapDoorBlock.WATERLOGGED,
                    false
                )
            )
        }

        override fun createBlockStateDefinition(builder: StateDefinition.Builder<Block, BlockState>) {
            super.createBlockStateDefinition(builder)
            (originalBlock as Block?)?.defaultBlockState()?.properties?.filterNot(EXISTING_DOOR_PROPERTIES::contains)
                ?.forEach(builder::add)
        }

        override fun getVisualBlockState(state: BlockState): BlockState {
            return this.originalBlock.withPropertiesOf(state)
        }

        companion object {
            val EXISTING_DOOR_PROPERTIES = listOf<Property<*>>(WATERLOGGED, HALF, OPEN, FACING, HINGE, POWERED)
        }
    }

    class DefaultAutoGenDoorBlock(settings: Properties, originalBlock: DoorSoundProvider) :
        AutoGenDimensionalDoorBlock<EntranceRiftBlockEntity.Impl>(settings, originalBlock) {
        override val riftBlockEnityType: BlockEntityType<EntranceRiftBlockEntity.Impl> get() = ModBlockEntityTypes.ENTRANCE_RIFT

        override fun useWithoutItem(
            state: BlockState,
            world: Level,
            pos: BlockPos,
            player: Player,
            hitResult: BlockHitResult
        ) = super.useWithoutItem(state, world, pos, player, hitResult)
    }

    abstract class AutoGenDimensionalTrapdoorBlock<T : EntranceRiftBlockEntity<T>>(
        settings: Properties,
        originalBlock: DoorSoundProvider
    ) : DimensionalTrapDoorBlock<T>(settings, originalBlock.setType), AutoGenTraversalRiftBlock<T> {
        override val originalBlock = originalBlock.cast<Block>()

        init {

            val builder = StateDefinition.Builder<Block, BlockState>(this)
            this.createBlockStateDefinition(builder)
            this.stateDefinition = builder.create(
                Block::defaultBlockState,
                ::BlockState
            )

            registerDefaultState(stateDefinition.any())
            registerDefaultState(withPropertiesOf(this.originalBlock.defaultBlockState()).setValue(WATERLOGGED, false))
        }

        override fun createBlockStateDefinition(builder: StateDefinition.Builder<Block, BlockState>) {
            super.createBlockStateDefinition(builder)
            (originalBlock as Block?)?.defaultBlockState()?.properties?.filterNot(EXISTING_TRAPDOOR_PROPERTIES::contains)
                ?.forEach(builder::add)
        }


        override fun getVisualBlockState(state: BlockState): BlockState = originalBlock.withPropertiesOf(state)

        companion object {
            val EXISTING_TRAPDOOR_PROPERTIES = listOf<Property<*>>(WATERLOGGED, HALF, OPEN, FACING, POWERED)
        }
    }

    class DefaultAutoGenTrapDoorBlock(settings: Properties, originalBlock: DoorSoundProvider) :
        AutoGenDimensionalTrapdoorBlock<EntranceRiftBlockEntity.Impl>(settings, originalBlock) {
        override val riftBlockEnityType: BlockEntityType<EntranceRiftBlockEntity.Impl>
            get() = ModBlockEntityTypes.ENTRANCE_RIFT
    }


    const val PREFIX: String = "block_ag_dim_"

    private val DEFAULT_PRODUCTION: DoorProduction = object : DoorProduction {
        override fun createDoor(context: GeneratedDoorContext, originalBlock: DoorBlock): Block {
            return DefaultAutoGenDoorBlock(context.properties, originalBlock)
        }

        override fun createTrapdoor(context: GeneratedDoorContext, originalBlock: TrapDoorBlock): Block {
            return DefaultAutoGenTrapDoorBlock(context.properties, originalBlock)
        }

        override fun onBlockRegistered(context: GeneratedDoorContext, generatedBlock: Block) {
            ModBlockEntityTypes.ENTRANCE_RIFT.addBlock(generatedBlock)
        }
    }

    private fun generatedId(location: ResourceLocation): ResourceLocation {
        return DimensionalDoors.id("$PREFIX${location.namespace}_${location.path}")
    }

    private fun createProperties(original: Block) = BlockBehaviour.Properties.ofFullCopy(original)
        .mapColor(original.defaultMapColor())
        .lightLevel { state -> original.withValuesOf(state).lightEmission }
        .isValidSpawn { state, level, pos, type -> original.withPropertiesOf(state).isValidSpawn(level, pos, type) }
        .isRedstoneConductor { state, level, pos -> original.withPropertiesOf(state).isRedstoneConductor(level, pos) }
        .isSuffocating { state, level, pos -> original.withPropertiesOf(state).isSuffocating(level, pos) }
        .isViewBlocking { state, level, pos -> original.withPropertiesOf(state).isViewBlocking(level, pos) }
        .hasPostProcess { state, level, pos -> original.withPropertiesOf(state).hasPostProcess(level, pos) }
        .emissiveRendering { state, level, pos -> original.withPropertiesOf(state).emissiveRendering(level, pos) }
        .requiresCorrectToolForDrops()

    private fun Block.withValuesOf(state: BlockState): BlockState = state.values.entries.fold(defaultBlockState()) { result, (property, value) ->
        if (result.hasProperty(property)) result.setValue(property as Property<Comparable<Any>>, value as Comparable<Any>) else result
    }

}
